import { promises as fs } from 'node:fs';
import fsSync from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { spawnSync } from 'node:child_process';

/**
 * M3 config writer: write the chosen model provider + API key into each
 * agent's own config file (design §8: Key 只写进 Agent 自己的配置，0600).
 *
 * Format notes: each writer targets the official config location with the
 * documented shape; exact field names are design-baseline and MUST be
 * re-verified against the agent's current docs during the M3 E2E pass
 * (same discipline as agents.json `verified`). `homeOverride` isolates
 * tests; production uses the real home dir.
 */

export async function writeProviderConfig({ agent, modelId, modelName, apiKey, baseUrl, anthropicBase, wireApi = 'chat', geminiEnv = null, geminiAuthType = 'gemini-api-key', homeOverride = null }) {
  const home = homeOverride || os.homedir();
  const kind = agent?.config?.kind;
  const out = { agentId: agent?.id, kind, status: 'ok', files: [], notes: [] };

  if (!apiKey) return { ...out, status: 'error', error: 'api-key-required' };
  if (!modelId && !modelName) return { ...out, status: 'error', error: 'model-required' };

  try {
    switch (kind) {
      case 'aider':
        await writeAider(home, out, modelName || modelId, apiKey, baseUrl);
        break;
      case 'codex':
        await writeCodex(home, out, modelId, modelName || modelId, apiKey, baseUrl, wireApi);
        break;
      case 'claude':
        await writeClaude(home, out, modelName || modelId, apiKey, anthropicBase || baseUrl);
        break;
      case 'opencode':
        await writeOpencode(home, out, modelId, modelName, apiKey, baseUrl);
        break;
      case 'hermes':
        await writeHermes(home, out, modelId, modelName || modelId, apiKey, baseUrl);
        break;
      case 'goose':
        await writeGoose(home, out, modelId, modelName || modelId, apiKey, baseUrl);
        break;
      case 'gemini':
        await writeGemini(home, out, modelName || modelId, apiKey, { env: geminiEnv, authType: geminiAuthType });
        break;
      default:
        return { ...out, status: 'unsupported', reason: `no-writer-for-kind:${kind}` };
    }
  } catch (err) {
    return { ...out, status: 'error', error: err?.message || String(err) };
  }
  return out;
}

async function writeFile0600(file, content) {
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, content, 'utf8');
  try {
    await fs.chmod(file, 0o600); // Unix
  } catch { /* Windows: no-op */ }
  if (process.platform === 'win32') {
    // Windows ACL: restrict to the current user (best effort).
    try {
      spawnSync('icacls', [file, '/inheritance:r', '/grant:r', `${process.env.USERNAME}:(R,W)`], { windowsHide: true, timeout: 8000 });
    } catch { /* best effort */ }
  }
}

/** Aider: ~/.aider.conf.yml (official config file, read on startup). */
async function writeAider(home, out, model, apiKey, baseUrl) {
  const file = path.join(home, '.aider.conf.yml');
  const body = [
    '# Generated by agent-guide (M3). Edit freely; re-run the wizard to regenerate.',
    `openai-api-base: ${baseUrl}`,
    `openai-api-key: ${apiKey}`,
    `openai-model: ${model}`,
    '',
  ].join('\n');
  await writeFile0600(file, body);
  out.files.push(file);
  out.notes.push('aider 通过 ~/.aider.conf.yml 使用 OpenAI 兼容端点；若官方字段变化请以 aider 文档为准。');
}

/**
 * Codex CLI & Desktop: ~/.codex/config.toml provider entry, aligned with the
 * format verified on a real machine (2026): inline experimental_bearer_token
 * (no env indirection), forced_login_method="api" so the desktop app skips
 * ChatGPT login, and wire_api per provider (deepseek = "responses", most
 * others = "chat"). auth.json is updated so the desktop app uses apikey auth.
 */
async function writeCodex(home, out, providerId, model, apiKey, baseUrl, wireApi) {
  const dir = path.join(home, '.codex');
  const file = path.join(dir, 'config.toml');
  const base = (baseUrl || '').replace(/\/+$/, '') + '/'; // codex expects trailing slash
  const body = [
    '# Generated by agent-guide (M3). Shared by Codex CLI and the Codex desktop app.',
    `model = "${model}"`,
    `model_provider = "${providerId}"`,
    'preferred_auth_method = "apikey"',
    'forced_login_method = "api"',
    '',
    `[model_providers.${providerId}]`,
    `name = "${providerId}"`,
    `base_url = "${base}"`,
    `wire_api = "${wireApi}"`,
    `experimental_bearer_token = "${apiKey}"`,
    '',
  ].join('\n');
  await writeFile0600(file, body);

  // Desktop app reads auth.json for apikey mode; merge to keep other fields.
  const authFile = path.join(dir, 'auth.json');
  let auth = {};
  try {
    auth = JSON.parse(await fs.readFile(authFile, 'utf8'));
  } catch { /* new file */ }
  auth.auth_mode = 'apikey';
  auth.OPENAI_API_KEY = apiKey;
  await writeFile0600(authFile, JSON.stringify(auth, null, 2) + '\n');

  out.files.push(file, authFile);
  out.notes.push(`codex：已写入 model_provider=${providerId}（wire_api=${wireApi}），CLI 与桌面版共用本配置；桌面版会用 API Key 登录而非 ChatGPT 账号。`);
}

/** Claude Code: ~/.claude/settings.json env block (anthropic-compatible endpoint). */
async function writeClaude(home, out, model, apiKey, endpoint) {
  const dir = path.join(home, '.claude');
  const file = path.join(dir, 'settings.json');
  let settings = {};
  try {
    settings = JSON.parse(await fs.readFile(file, 'utf8'));
  } catch { /* new file */ }
  settings.env = {
    ...(settings.env || {}),
    ANTHROPIC_BASE_URL: endpoint,
    ANTHROPIC_AUTH_TOKEN: apiKey,
    ANTHROPIC_MODEL: model,
  };
  await writeFile0600(file, JSON.stringify(settings, null, 2) + '\n');
  out.files.push(file);
  out.notes.push('claude 通过 ~/.claude/settings.json 的 env 指向 Anthropic 兼容端点；router 场景（M4）会改为本地 router 地址。');
}

/** OpenCode: ~/.config/opencode/config.json provider block (openai-compatible). */
async function writeOpencode(home, out, modelId, modelName, apiKey, baseUrl) {
  const dir = process.platform === 'win32'
    ? path.join(home, '.config', 'opencode')
    : path.join(home, '.config', 'opencode');
  const file = path.join(dir, 'config.json');
  let cfg = {};
  try {
    cfg = JSON.parse(await fs.readFile(file, 'utf8'));
  } catch { /* new file */ }
  const providerId = 'agent-guide';
  cfg.provider = cfg.provider || {};
  cfg.provider[providerId] = {
    npm: '@ai-sdk/openai-compatible',
    name: 'agent-guide provider',
    options: { baseURL: baseUrl, apiKey },
    models: {
      [modelId]: { name: modelName || modelId },
    },
  };
  await writeFile0600(file, JSON.stringify(cfg, null, 2) + '\n');
  out.files.push(file);
  out.notes.push('opencode 通过 config.json 的 provider 块接入 OpenAI 兼容端点；字段为设计基准，请按 opencode 文档复核。');
}

/**
 * Map a provider id to the env-var prefix used by hermes/goose (official docs:
 * DEEPSEEK_API_KEY/DEEPSEEK_BASE_URL, DASHSCOPE_*, GLM_*, …). Unknown ids fall
 * back to the uppercased base id (best effort, surfaced in writer notes).
 */
const PROVIDER_ENV_PREFIX = {
  // 与 provider id 不同的大写前缀（其余按 id 大写兜底）
  qwen: 'DASHSCOPE',
  zhipu: 'GLM',
};
export function providerEnvPrefix(modelId) {
  const base = ((modelId || '').split('-')[0] || '').toLowerCase();
  return (PROVIDER_ENV_PREFIX[base] || base).toUpperCase() || 'PROVIDER';
}

/**
 * Hermes: ~/.hermes/.env. Variable names verified against the official
 * Environment Variables reference (hermes-agent.nousresearch.com): per-provider
 * <PREFIX>_API_KEY / <PREFIX>_BASE_URL (DEEPSEEK_*, DASHSCOPE_*, GLM_*, …) plus
 * HERMES_MODEL. (HERMES_API_KEY / HERMES_BASE_URL are NOT official names.)
 */
async function writeHermes(home, out, providerId, model, apiKey, baseUrl) {
  const dir = path.join(home, '.hermes');
  const file = path.join(dir, '.env');
  const prefix = providerEnvPrefix(providerId);
  const body = [
    '# Generated by agent-guide (M3). Names verified against the official',
    '# Hermes Agent environment-variables reference.',
    `HERMES_MODEL=${model}`,
    `${prefix}_BASE_URL=${baseUrl}`,
    `${prefix}_API_KEY=${apiKey}`,
    '',
  ].join('\n');
  await writeFile0600(file, body);
  out.files.push(file);
  out.notes.push(`hermes 已写入官方变量 HERMES_MODEL + ${prefix}_BASE_URL/${prefix}_API_KEY（见官方 environment-variables 文档）；官方推荐用 \`hermes model\` 命令管理模型。`);
}

/**
 * Goose: ~/.config/goose/custom_providers/<id>.json (official docs:
 * mintlify.wiki/block/goose/api/providers/custom). Registers an
 * OpenAI-compatible provider; the API key is read from the env var named by
 * `api_key_env`, so the server layer persists that env var (setx / shell
 * profile). `out.envKey` carries the env var NAME only — never the key value.
 */
async function writeGoose(home, out, providerId, model, apiKey, baseUrl) {
  const dir = path.join(home, '.config', 'goose', 'custom_providers');
  const file = path.join(dir, `${providerId}.json`);
  const prefix = providerEnvPrefix(providerId);
  const envKey = `${prefix}_API_KEY`;
  const provider = {
    name: providerId,
    engine: 'openai',
    display_name: `agent-guide ${providerId}`,
    description: 'Configured by the agent-guide wizard',
    api_key_env: envKey,
    base_url: (baseUrl || '').replace(/\/+$/, ''),
    // deepseek-v4* advertises a 1M context window; conservative default otherwise.
    models: [{ name: model, context_limit: providerId === 'deepseek' ? 1048576 : 128000 }],
    requires_auth: true,
    supports_streaming: true,
    base_path: 'v1/chat/completions',
  };
  await writeFile0600(file, JSON.stringify(provider, null, 2) + '\n');
  out.files.push(file);
  out.envKey = envKey;
  out.notes.push(`goose：已注册 provider ${providerId}（custom_providers/${providerId}.json，engine=openai）；API Key 由环境变量 ${envKey} 提供（向导已持久化，新开终端生效）；请在 goose 中运行 \`goose configure\` 选择该 provider 与模型。`);
}

/**
 * Persist user-level environment variables so new terminal sessions (and thus
 * `gemini`) see them. Windows uses `setx`; macOS/Linux appends `export` lines
 * to the first existing shell profile (~/.bashrc → ~/.zshrc → ~/.profile).
 *
 * Returns { commands, notes } — commands are always listed (transparency);
 * `dryRun` skips the actual execution. This is what makes the GCR gateway
 * base URL (`GOOGLE_GEMINI_BASE_URL`) reach the installed gemini-cli, which
 * reads that var from the real process env only (settings.json `env` is not
 * injected into process.env by current gemini-cli versions).
 */
export function persistUserEnvVars(vars, { dryRun = false, homeOverride = null } = {}) {
  const commands = [];
  const notes = [];
  for (const [k, v] of Object.entries(vars || {})) {
    if (process.platform === 'win32') {
      const cmd = `setx ${k} "${v}"`;
      commands.push(cmd);
      if (dryRun) { notes.push(`[dry-run] ${cmd}`); continue; }
      try {
        const r = spawnSync('setx', [k, String(v)], { windowsHide: true, timeout: 15000 });
        notes.push(r.status === 0
          ? `已写入用户环境变量 ${k}（新开的终端生效）`
          : `setx ${k} 失败：请手动执行 ${cmd}`);
      } catch {
        notes.push(`setx ${k} 失败：请手动执行 ${cmd}`);
      }
    } else {
      const home = homeOverride || os.homedir();
      const candidates = ['.bashrc', '.zshrc', '.profile'].map((n) => path.join(home, n));
      let target = null;
      for (const f of candidates) {
        try { fsSync.accessSync(f); target = f; break; } catch { /* next */ }
      }
      if (!target) target = path.join(home, '.profile');
      const cmd = `echo 'export ${k}="${v}"' >> ${target}`;
      commands.push(cmd);
      if (dryRun) { notes.push(`[dry-run] ${cmd}`); continue; }
      try {
        const body = `# agent-guide (gemini)\nexport ${k}="${v}"\n`;
        fsSync.appendFileSync(target, body);
        notes.push(`已追加 export ${k}=… 到 ${target}（新开的终端生效）`);
      } catch {
        notes.push(`写入 ${target} 失败：请手动执行 ${cmd}`);
      }
    }
  }
  return { commands, notes };
}

/**
 * Gemini CLI: ~/.gemini/settings.json.
 *
 * 关键机制（依据已安装 gemini-cli 交互式源码核实）：
 * - 引导开关：只有 `security.auth.selectedType` 未设置时，gemini 才会弹出
 *   "How would you like to authenticate for this project?" 选择器；写入该字段
 *   后直接按对应方式鉴权，永不弹引导。
 * - apiKey 解析：`apiKey(参数) → settings.env.GEMINI_API_KEY → 进程环境
 *   GEMINI_API_KEY → 系统钥匙串`，所以 settings 里同时写顶层 apiKey 和
 *   env.GEMINI_API_KEY 最稳。
 * - gateway（AI API Gateway，GCR 代理）：baseUrl 只读进程环境变量
 *   `GOOGLE_GEMINI_BASE_URL`（settings.env 不会注入 process.env），因此
 *   server 层还需要持久化该环境变量（setx / shell profile）。
 * - 0.56.0 实测：validateAuthMethod 只接受 oauth-personal /
 *   compute-default-credentials / gemini-api-key / vertex-ai，`gateway` 值会被
 *   拒绝（exit 41 "Invalid auth method selected."）；且 settings.model 必须是
 *   对象 `{ default: <model> }`（字符串报 "Expected object, received string"）。
 *   因此 GCR 场景统一写 selectedType=gemini-api-key（占位 Key）+ 环境变量 baseUrl，
 *   网关探测由 gemini-cli 依据 GOOGLE_GEMINI_BASE_URL 自动完成。
 *
 * 已有 settings.json 会先读取并合并（保留 OAuth 等其它字段）；selectedType
 * 会被覆盖为本次写入的认证方式（修正之前残留的 oauth-personal 死循环）。
 */
async function writeGemini(home, out, model, apiKey, { env = null, authType = 'gemini-api-key' } = {}) {
  const file = path.join(home, '.gemini', 'settings.json');
  let settings = {};
  try {
    settings = JSON.parse(await fs.readFile(file, 'utf8'));
  } catch { /* new file */ }
  settings.apiKey = apiKey;
  // gemini-cli 0.56.0 拒绝 'gateway' 作为 selectedType（validateAuthMethod 校验）；
  // GCR 场景的正确姿势是 gemini-api-key + 占位 Key + GOOGLE_GEMINI_BASE_URL 环境变量。
  // 历史调用方传的 'gateway' 在此归一为合法值，保证写出的文件永远可被 CLI 接受。
  const effectiveAuth = authType === 'gateway' ? 'gemini-api-key' : authType;
  // gemini-cli 0.56.0 的 settings.model 必须是对象（{ default: <model> }）。
  // GCR 场景模型由代理转发，写 default 仅用于 CLI 展示，无副作用。
  if (model) settings.model = { default: model };
  settings.env = { ...(settings.env || {}), GEMINI_API_KEY: apiKey, ...(env || {}) };
  settings.security = {
    ...(settings.security || {}),
    auth: { ...(settings.security?.auth || {}), selectedType: effectiveAuth },
  };
  await writeFile0600(file, JSON.stringify(settings, null, 2) + '\n');
  out.files.push(file);
  if (authType === 'gateway') {
    out.notes.push('gemini：selectedType=gemini-api-key（占位 Key，gemini-cli 0.56.0 不接受 gateway 值）+ env 已写 GEMINI_API_KEY / GEMINI_BASE_URL / GOOGLE_GEMINI_BASE_URL；baseUrl 需由向导持久化到系统环境变量才对该版本生效。');
  } else {
    out.notes.push('gemini：security.auth.selectedType=gemini-api-key（不再弹 Get started 登录引导），API Key 已写入 settings.json 的 apiKey 与 env.GEMINI_API_KEY。');
  }
}
