import { promises as fs } from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { spawnSync } from 'node:child_process';

/**
 * M3 config writer: write the chosen model provider + API key into each
 * agent's own config file (design §8: Key 只写进 Agent 自己的配置，0600).
 *
 * Format notes: each writer targets the official config location with the
 * documented shape; exact field names are design-baseline and MUST be
 * re-verified against the agent's current docs during the M3 E2E pass
 * (same discipline as agents.json `verified`). `homeOverride` isolates
 * tests; production uses the real home dir.
 */

export async function writeProviderConfig({ agent, modelId, modelName, apiKey, baseUrl, anthropicBase, homeOverride = null }) {
  const home = homeOverride || os.homedir();
  const kind = agent?.config?.kind;
  const out = { agentId: agent?.id, kind, status: 'ok', files: [], notes: [] };

  if (!apiKey) return { ...out, status: 'error', error: 'api-key-required' };
  if (!modelId && !modelName) return { ...out, status: 'error', error: 'model-required' };

  try {
    switch (kind) {
      case 'aider':
        await writeAider(home, out, modelName || modelId, apiKey, baseUrl);
        break;
      case 'codex':
        await writeCodex(home, out, modelName || modelId, apiKey, baseUrl);
        break;
      case 'claude':
        await writeClaude(home, out, modelName || modelId, apiKey, anthropicBase || baseUrl);
        break;
      case 'opencode':
        await writeOpencode(home, out, modelId, modelName, apiKey, baseUrl);
        break;
      case 'hermes':
        await writeHermes(home, out, modelName || modelId, apiKey, baseUrl);
        break;
      case 'gemini':
        return { ...out, status: 'unsupported', reason: 'gemini-agents-use-google-auth' };
      default:
        return { ...out, status: 'unsupported', reason: `no-writer-for-kind:${kind}` };
    }
  } catch (err) {
    return { ...out, status: 'error', error: err?.message || String(err) };
  }
  return out;
}

async function writeFile0600(file, content) {
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, content, 'utf8');
  try {
    await fs.chmod(file, 0o600); // Unix
  } catch { /* Windows: no-op */ }
  if (process.platform === 'win32') {
    // Windows ACL: restrict to the current user (best effort).
    try {
      spawnSync('icacls', [file, '/inheritance:r', '/grant:r', `${process.env.USERNAME}:(R,W)`], { windowsHide: true, timeout: 8000 });
    } catch { /* best effort */ }
  }
}

/** Aider: ~/.aider.conf.yml (official config file, read on startup). */
async function writeAider(home, out, model, apiKey, baseUrl) {
  const file = path.join(home, '.aider.conf.yml');
  const body = [
    '# Generated by agent-guide (M3). Edit freely; re-run the wizard to regenerate.',
    `openai-api-base: ${baseUrl}`,
    `openai-api-key: ${apiKey}`,
    `openai-model: ${model}`,
    '',
  ].join('\n');
  await writeFile0600(file, body);
  out.files.push(file);
  out.notes.push('aider 通过 ~/.aider.conf.yml 使用 OpenAI 兼容端点；若官方字段变化请以 aider 文档为准。');
}

/** Codex CLI: ~/.codex/config.toml with a model_providers entry. */
async function writeCodex(home, out, model, apiKey, baseUrl) {
  const dir = path.join(home, '.codex');
  const file = path.join(dir, 'config.toml');
  const providerId = 'agent-guide';
  const body = [
    '# Generated by agent-guide (M3).',
    `model = "${model}"`,
    `model_provider = "${providerId}"`,
    '',
    `[model_providers.${providerId}]`,
    'name = "agent-guide provider"',
    `base_url = "${baseUrl}"`,
    `env_key = "AGENT_GUIDE_API_KEY"`,
    'wire_api = "chat"',
    '',
  ].join('\n');
  await writeFile0600(file, body);
  // Codex reads the key from the env var named above; ship it in ~/.codex/.env
  // (agent-guide sets it when launching through the wizard as well).
  const envFile = path.join(dir, '.env');
  await writeFile0600(envFile, `AGENT_GUIDE_API_KEY=${apiKey}\n`);
  out.files.push(file, envFile);
  out.notes.push('codex 配置：model_providers 使用 env_key + ~/.codex/.env；字段为设计基准，请按 codex 官方文档复核。');
}

/** Claude Code: ~/.claude/settings.json env block (anthropic-compatible endpoint). */
async function writeClaude(home, out, model, apiKey, endpoint) {
  const dir = path.join(home, '.claude');
  const file = path.join(dir, 'settings.json');
  let settings = {};
  try {
    settings = JSON.parse(await fs.readFile(file, 'utf8'));
  } catch { /* new file */ }
  settings.env = {
    ...(settings.env || {}),
    ANTHROPIC_BASE_URL: endpoint,
    ANTHROPIC_AUTH_TOKEN: apiKey,
    ANTHROPIC_MODEL: model,
  };
  await writeFile0600(file, JSON.stringify(settings, null, 2) + '\n');
  out.files.push(file);
  out.notes.push('claude 通过 ~/.claude/settings.json 的 env 指向 Anthropic 兼容端点；router 场景（M4）会改为本地 router 地址。');
}

/** OpenCode: ~/.config/opencode/config.json provider block (openai-compatible). */
async function writeOpencode(home, out, modelId, modelName, apiKey, baseUrl) {
  const dir = process.platform === 'win32'
    ? path.join(home, '.config', 'opencode')
    : path.join(home, '.config', 'opencode');
  const file = path.join(dir, 'config.json');
  let cfg = {};
  try {
    cfg = JSON.parse(await fs.readFile(file, 'utf8'));
  } catch { /* new file */ }
  const providerId = 'agent-guide';
  cfg.provider = cfg.provider || {};
  cfg.provider[providerId] = {
    npm: '@ai-sdk/openai-compatible',
    name: 'agent-guide provider',
    options: { baseURL: baseUrl, apiKey },
    models: {
      [modelId]: { name: modelName || modelId },
    },
  };
  await writeFile0600(file, JSON.stringify(cfg, null, 2) + '\n');
  out.files.push(file);
  out.notes.push('opencode 通过 config.json 的 provider 块接入 OpenAI 兼容端点；字段为设计基准，请按 opencode 文档复核。');
}

/** Hermes: ~/.hermes/.env with provider vars (variable names are design-baseline). */
async function writeHermes(home, out, model, apiKey, baseUrl) {
  const dir = path.join(home, '.hermes');
  const file = path.join(dir, '.env');
  const body = [
    '# Generated by agent-guide (M3). Variable names are design-baseline.',
    `HERMES_MODEL=${model}`,
    `HERMES_BASE_URL=${baseUrl}`,
    `HERMES_API_KEY=${apiKey}`,
    '',
  ].join('\n');
  await writeFile0600(file, body);
  out.files.push(file);
  out.notes.push('hermes 模型配置官方走 `hermes model` 命令；本文件为向导写入的通用变量（设计基准），请以 hermes 文档复核。');
}
