import { spawn, spawnSync } from 'node:child_process';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import net from 'node:net';
import { stateDir } from './state.js';

/**
 * M4 router lifecycle manager.
 *
 * Claude Code Router (CCR, @musistudio/claude-code-router 3.x): a local
 * management service + Anthropic-compatible gateway. Claude Code points its
 * ANTHROPIC_BASE_URL at the gateway; the gateway translates to an upstream
 * OpenAI-compatible provider (DeepSeek / Kimi / GLM / …).
 *
 * `binOverride` lets tests inject a fake `ccr` executable; production uses
 * the globally installed `ccr` (or `npx` when absent).
 */

const CCR_PKG = '@musistudio/claude-code-router';
export const CCR_VERSION = '3.0.21';

const GCR_PKG = 'gemini-cli-router';
export const GCR_VERSION = '1.0.3';
export const GCR_DEFAULT_PORT = 3458;

/**
 * Write the GCR (gemini-cli-router) provider config into
 * ~/.gemini-cli-router/.env. The proxy reads these vars at startup
 * (proxy-service/src/config.js): GCR_PROVIDER selects the built-in provider
 * table; GCR_BASE_URL / GCR_MODEL override the built-ins (which still carry
 * legacy deepseek-chat /v1 values). `homeOverride` isolates tests.
 */
export async function writeGcrEnv({ provider = 'deepseek', baseUrl, model, apiKey, port = GCR_DEFAULT_PORT, homeOverride = null } = {}) {
  const dir = path.join(homeOverride || os.homedir(), '.gemini-cli-router');
  const file = path.join(dir, '.env');
  const lines = [
    '# Generated by agent-guide (M4). Keys live only in this file (0600).',
    `GCR_PROVIDER=${provider}`,
    `GCR_BASE_URL=${baseUrl}`,
    `GCR_TARGET_API_KEY=${apiKey}`,
    `GCR_MODEL=${model}`,
    `GCR_PORT=${port}`,
    'GCR_HOST=127.0.0.1',
    'GCR_DEBUG=false',
    '',
  ];
  await fs.mkdir(dir, { recursive: true });
  await fs.writeFile(file, lines.join('\n'), 'utf8');
  try { await fs.chmod(file, 0o600); } catch { /* Windows */ }
  return { file };
}

/**
 * Run npm through the shell on Windows (npm is a .cmd shim; spawnSync('npm')
 * fails with EINVAL inside a node process, same trap as detect.js).
 */
function npmSync(args, timeout = 300000) {
  if (process.platform === 'win32') {
    return spawnSync('cmd.exe', ['/d', '/s', '/c', `npm ${args.join(' ')}`], {
      windowsHide: true, timeout, encoding: 'utf8',
    });
  }
  return spawnSync('npm', args, { windowsHide: true, timeout, encoding: 'utf8' });
}

export function globalNpmRoot() {
  const r = npmSync(['root', '-g'], 15000);
  return (r.stdout || '').trim() || null;
}

/** Is the GCR package installed globally? (file check — no npm invocation) */
export function gcrPackagePath() {
  const root = globalNpmRoot();
  return root ? path.join(root, GCR_PKG) : null;
}

export async function isGcrInstalled() {
  const pkg = gcrPackagePath();
  if (!pkg) return false;
  try {
    await fs.access(pkg);
    return true;
  } catch {
    return false;
  }
}

async function installGcr(log = () => {}) {
  log(`npm install -g ${GCR_PKG}@${GCR_VERSION}`);
  const r = npmSync(['install', '-g', `${GCR_PKG}@${GCR_VERSION}`]);
  if (r.status !== 0) return { ok: false, error: r.stderr?.slice(0, 500) || `npm exit ${r.status}` };
  return { ok: true };
}

/**
 * Probe the GCR proxy health endpoint. GCR's proxy binds ::1 (IPv6 loopback)
 * on some platforms, so probe both 127.0.0.1 and [::1].
 */
export async function gcrHealthy(port = GCR_DEFAULT_PORT) {
  for (const host of ['127.0.0.1', '[::1]']) {
    try {
      const controller = new AbortController();
      const t = setTimeout(() => controller.abort(), 1500);
      const res = await fetch(`http://${host}:${port}/health`, { signal: controller.signal });
      clearTimeout(t);
      if (res.ok) return true;
    } catch { /* try next address */ }
  }
  return false;
}

/**
 * Start the GCR proxy: ensure installed → write .env → spawn
 * `start-gemini-proxy` detached → poll /health. dryRun skips everything
 * except writing the config (tests).
 */
/**
 * Resolve the GCR proxy launch command.
 * The package's `start-gemini-proxy` bin is a bash script — npm's Windows
 * shim tries /bin/bash.exe and fails. The package ships a Windows-friendly
 * `start-gemini-proxy.cjs`; run it via node on win32, the bin elsewhere.
 */
export function gcrLaunchCommand() {
  if (process.platform === 'win32') {
    const root = globalNpmRoot();
    const cjs = root ? path.join(root, 'gemini-cli-router', 'bundle', 'start-gemini-proxy.cjs') : null;
    if (cjs) return { cmd: process.execPath, args: [cjs] };
    // fall back to the shim (may fail on bash-less Windows, but try)
    return { cmd: 'start-gemini-proxy', args: [] };
  }
  return { cmd: 'start-gemini-proxy', args: [] };
}

export async function gcrStart({ port = GCR_DEFAULT_PORT, provider = 'deepseek', baseUrl, model, apiKey, dryRun = false, log = () => {} } = {}) {
  const envFile = await writeGcrEnv({ provider, baseUrl, model, apiKey, port, homeOverride: process.env.AGENT_GUIDE_HOME || null });
  if (dryRun) {
    return { ok: true, dryRun: true, port, envFile: envFile.file };
  }
  // Reuse a proxy that is already healthy on this port.
  if (await gcrHealthy(port)) {
    return { ok: true, running: true, alreadyRunning: true, port, envFile: envFile.file };
  }
  if (!(await isGcrInstalled())) {
    const installed = await installGcr(log);
    if (!installed.ok) return { ok: false, error: `gemini-cli-router install failed: ${installed.error}` };
  }
  const { cmd, args } = gcrLaunchCommand();
  if (!cmd || (process.platform === 'win32' && !args.length)) {
    return { ok: false, error: '无法定位 GCR 启动器（npm 全局目录未找到 gemini-cli-router）' };
  }
  log(`${cmd} ${args.join(' ')} (port ${port})`);
  const child = spawn(cmd, args, { detached: true, stdio: 'ignore', windowsHide: true });
  child.unref();
  let ready = false;
  for (let i = 0; i < 20; i++) {
    await new Promise((r) => setTimeout(r, 500));
    if (await gcrHealthy(port)) { ready = true; break; }
  }
  if (!ready) {
    return { ok: false, error: `GCR 代理启动后 10 秒内未通过健康检查 (http://localhost:${port}/health)。请确认 3458 端口空闲后重试。` };
  }
  return { ok: true, running: true, port, envFile: envFile.file };
}

/** Stop the GCR proxy by killing the process listening on its port. */
export async function gcrStop({ port = GCR_DEFAULT_PORT, dryRun = false } = {}) {
  if (dryRun) return { ok: true, dryRun: true, running: false };
  if (!(await gcrHealthy(port))) return { ok: true, running: false, alreadyStopped: true };
  // Windows: taskkill the owning process of the listening port.
  const r = spawnSync('powershell', [
    '-NoProfile', '-Command',
    `$c = Get-NetTCPConnection -LocalPort ${port} -State Listen -ErrorAction SilentlyContinue; if ($c) { $c | Select-Object -First 1 | ForEach-Object { Stop-Process -Id $_.OwningProcess -Force } }; 'done'`,
  ], { windowsHide: true, timeout: 15000, encoding: 'utf8' });
  return { ok: r.status === 0, running: false, output: r.stdout?.slice(0, 100) };
}

/** Combined GCR status. */
export async function gcrStatus({ port = GCR_DEFAULT_PORT } = {}) {
  const running = await gcrHealthy(port);
  const installed = await isGcrInstalled();
  return { installed, running, port, healthUrl: `http://127.0.0.1:${port}/health` };
}

export function routerDir() {
  return path.join(stateDir(), 'router');
}

export function routerStateFile() {
  return path.join(routerDir(), 'router.json');
}

/** CCR requires Node >= 22 (our wizard baseline is 20). */
export function ccrNodeOk(nodeVersion = process.version) {
  const m = /v?(\d+)\./.exec(nodeVersion || '');
  const major = m ? parseInt(m[1], 10) : 0;
  return major >= 22;
}

function ccrCmd(binOverride) {
  return binOverride || 'ccr';
}

/** Check whether a TCP port is currently listening. */
export function isPortOpen(port, host = '127.0.0.1') {
  return new Promise((resolve) => {
    const sock = net.connect({ port, host, timeout: 1200 });
    sock.once('connect', () => { sock.destroy(); resolve(true); });
    sock.once('error', () => { sock.destroy(); resolve(false); });
    sock.once('timeout', () => { sock.destroy(); resolve(false); });
  });
}

export async function readRouterState() {
  try {
    return JSON.parse(await fs.readFile(routerStateFile(), 'utf8'));
  } catch {
    return { installed: false, running: false, port: null, gatewayPort: null, provider: null, updatedAt: null };
  }
}

async function writeRouterState(state) {
  await fs.mkdir(routerDir(), { recursive: true });
  await fs.writeFile(routerStateFile(), JSON.stringify({ ...state, updatedAt: new Date().toISOString() }, null, 2), 'utf8');
}

/** Is the ccr CLI available on PATH? */
export async function isCcrInstalled(binOverride = null) {
  if (binOverride) {
    const r = spawnSync(binOverride, ['--version'], { windowsHide: true, timeout: 8000, encoding: 'utf8' });
    return r.status === 0;
  }
  const r = spawnSync('ccr', ['--version'], { windowsHide: true, timeout: 8000, encoding: 'utf8' });
  return r.status === 0;
}

/** Install CCR globally via npm (pinned version, per design §8 supply chain). */
export async function installCcr(log = () => {}) {
  log(`npm install -g ${CCR_PKG}@${CCR_VERSION}`);
  const r = npmSync(['install', '-g', `${CCR_PKG}@${CCR_VERSION}`]);
  if (r.status !== 0) {
    return { ok: false, error: r.stderr?.slice(0, 500) || `npm exit ${r.status}` };
  }
  await writeRouterState({ installed: true, running: false, port: null, gatewayPort: null, provider: null });
  return { ok: true };
}

/**
 * Start the CCR management service + gateway on a preferred port.
 * `ccr start --host 127.0.0.1 --port <port> --no-open` runs detached; we then
 * poll the port (management UI) and read gateway.config.json for the gateway
 * port when available. `dryRun` skips the actual spawn (tests/CI).
 */
export async function startCcr({ port, binOverride = null, dryRun = false, skipInstall = false, log = () => {} } = {}) {
  const state = await readRouterState();
  const chosen = port || 3458;
  if (dryRun) {
    await writeRouterState({ ...state, installed: true, running: true, port: chosen, gatewayPort: chosen + 1 });
    return { ok: true, dryRun: true, port: chosen, gatewayPort: chosen + 1, managementUrl: `http://127.0.0.1:${chosen}` };
  }
  if (!skipInstall && !(await isCcrInstalled(binOverride))) {
    const installed = await installCcr(log);
    if (!installed.ok) return { ok: false, error: `ccr install failed: ${installed.error}` };
  }
  if (state.running) return { ok: true, ...state, alreadyRunning: true };

  const cmd = ccrCmd(binOverride);
  log(`ccr start --host 127.0.0.1 --port ${chosen} --no-open`);
  let child;
  try {
    child = spawn(cmd, ['start', '--host', '127.0.0.1', '--port', String(chosen), '--no-open'], {
      detached: true,
      stdio: 'ignore',
      windowsHide: true,
    });
  } catch (err) {
    await writeRouterState({ ...state, running: false, port: chosen });
    return { ok: false, error: `ccr spawn failed: ${err?.message || err}` };
  }
  let spawnFailed = null;
  child.on('error', (err) => { spawnFailed = err?.message || String(err); });
  child.unref();

  // Poll the management port until it answers (or timeout).
  let ready = false;
  for (let i = 0; i < 20; i++) {
    await new Promise((r) => setTimeout(r, 500));
    if (spawnFailed) break;
    if (await isPortOpen(chosen)) { ready = true; break; }
  }
  if (spawnFailed) {
    await writeRouterState({ ...state, running: false, port: chosen });
    return { ok: false, error: `ccr spawn failed: ${spawnFailed}` };
  }
  const gatewayPort = await discoverGatewayPort();
  await writeRouterState({ ...state, installed: true, running: ready, port: chosen, gatewayPort });
  return { ok: ready, running: ready, port: chosen, gatewayPort, managementUrl: `http://127.0.0.1:${chosen}` };
}

/** Read the gateway port from CCR's generated runtime config, if present. */
async function discoverGatewayPort() {
  for (const dir of [
    path.join(os.homedir(), '.claude-code-router'),
    path.join(os.homedir(), '.config', 'claude-code-router'),
    path.join(os.homedir(), 'AppData', 'Roaming', 'claude-code-router'),
  ]) {
    try {
      const raw = await fs.readFile(path.join(dir, 'gateway.config.json'), 'utf8');
      const cfg = JSON.parse(raw);
      const p = cfg?.port ?? cfg?.gateway?.port ?? cfg?.server?.port;
      if (typeof p === 'number') return p;
    } catch { /* try next */ }
  }
  return null;
}

/** Stop the CCR detached service. */
export async function stopCcr({ binOverride = null, dryRun = false } = {}) {
  const state = await readRouterState();
  if (!state.running && !dryRun) return { ok: true, running: false, alreadyStopped: true };
  if (dryRun) {
    await writeRouterState({ ...state, running: false, port: null });
    return { ok: true, dryRun: true, running: false };
  }
  const r = spawnSync(ccrCmd(binOverride), ['stop'], { windowsHide: true, timeout: 30000, encoding: 'utf8' });
  await writeRouterState({ ...state, running: r.status === 0, port: r.status === 0 ? null : state.port });
  return { ok: r.status === 0, running: false, output: r.stdout?.slice(0, 200) };
}

/** Combined status: installed? running? ports? */
export async function statusCcr({ binOverride = null } = {}) {
  const state = await readRouterState();
  const installed = await isCcrInstalled(binOverride);
  const portOpen = state.port ? await isPortOpen(state.port) : false;
  return {
    installed,
    running: portOpen || state.running === true,
    port: state.port,
    gatewayPort: state.gatewayPort,
    managementUrl: state.port ? `http://127.0.0.1:${state.port}` : null,
    nodeOk: ccrNodeOk(),
    note: ccrNodeOk() ? null : 'CCR 需要 Node.js ≥ 22（当前 Node 较低，请升级后重试）',
  };
}
